#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Func Da World"
email: oskar.wickstrom@gmail.com
description: >
  Oskar Wickstr√∂m on functional programming.
baseurl: "/func-da-world"
url: "https://owickstrom.github.io"
twitter_username: owickstrom
github_username:  owickstrom

navigation:
  - text: Archive
    url: /blog-test/archive.html
  - text: About
    url: /blog-test/about.html

# Build settings
markdown: Pandoc

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-pandoc

pandoc:
  extensions:
    #- 'implicit_figures'
    highlight-style: pygments
